site_name: RTR2
site_description: Real-time 3D rendering engine with Vulkan and Slang
repo_url: https://github.com/annajcy/rtr2
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: material/cube-outline
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: annajcy/rtr2

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - i18n:
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Documentation:
      - Overview: documentation/overview.md
      - System:
          - Physics:
              - Overview: documentation/system/physics/overview.md
              - Rigid Body Dynamics: documentation/system/physics/rigid-body-dynamics.md
      - Utils: documentation/utils.md
  - Profiling:
      - MacOS: profiling/macos.md
  - Slang Tutorial:
      - Overview: slang-tutorial/overview.md
      - Basics:
          - Overview: slang-tutorial/basics/overview.md
          - Lesson 1: slang-tutorial/basics/lesson-1.md
  - API: api/index.md
